### ISSUE TITLE
not working with source kafka 0.11.0.3 and destination 1.1.1

### ISSUE THREAD

**Issue by piyuverma** [Comcast/MirrorTool-for-Kafka-Connect#19]
I am getting this issue: it does not seem looking at the error that, it is because of incompatibility of kafka versions:
```
java.lang.NoSuchMethodError: com.comcast.kafka.connect.kafka.KafkaSourceConnectorConfig.originalsWithPrefix(Ljava/lang/String;Z)Ljava/util/Map;
at com.comcast.kafka.connect.kafka.KafkaSourceConnectorConfig.allWithPrefix(KafkaSourceConnectorConfig.java:184)
```

Please suggest, if i am missing something.

**Comment by rhysmccaig** [comment]
Hi @piyuverma,

I haven't tested this with Kafka versions < 2.0, so I'm not sure if it is related to version compatibility. 

Can you give more details about your environment? What version of java are you using? What version of Kafka Connect?

**Comment by piyuverma** [comment]
Hi @rhysmccaig, 
I am using JAVA JDK 1.8 and KAFKA_CONFLUENT_VERSION=3.3.3, building connect FROM confluentinc/cp-kafka-connect-base:3.3.3.

**Comment by rhysmccaig** [comment]
@piyuverma confluent version 3.3.3 uses Kafka version 0.11.0.0, which unfortunately does not contain the `originalsWithPrefix(String, bool)` method. 
It looks like it was added in Kafka 1.0: 
Compare: `https://kafka.apache.org/0110/javadoc/org/apache/kafka/common/config/AbstractConfig.html`
with 
`https://kafka.apache.org/10/javadoc/org/apache/kafka/common/config/AbstractConfig.html`

In order for this connector to work you will need to upgrade to a newer version of Kafka connect (Preferably Kafka version 2+, but 1.1 may work.)
